### ISSUE TITLE
Error: object 'quartz' is not exported by 'namespace:grDevices'

### ISSUE THREAD

**Issue by chimidata** [kumeS/agGraphSearch#1]
At installing 'agGraphSearch', 'Error: object 'quartz' is not exported by 'namespace:grDevices'' occured.
I think 'quartz' is package only for macOS. But I would like install it in Windows 10(64bit) environment.
![R_quartz_error](https://user-images.githubusercontent.com/51772032/204191479-03144234-9984-448b-b8f6-500253ccd346.png)
 
Let me know how to resolve the issue.

Thank you for your kind.

**Comment by kumeS** [comment]
Hi @chimidata, I have not tested this package on Windows system.
I think that this package coding is based on the coding worked on Mac OS X. So it does not work well on Windows system.
I will check Mac specific coding in this package. Please wait a while to modify this package.

**Comment by kumeS** [comment]
Hi @chimidata, I have not tested this package on Windows system.
I think that this package coding is based on the coding worked on Mac OS X. So it does not work well on Windows system.
I will check Mac specific coding in this package. Please wait a while to modify this package.

**Comment by chimidata** [comment]
@kumeS
Thank you for your reply.
I try to add the preferce setting in .Rprofile for Windows. To resolve the issue, probabliy, Platform$OS.type or options(device="") will be described in the profile.
Thank you.

**Comment by kumeS** [comment]
@chimidata Please try this code to install the package. Probably OK.

```
#install SPARQL_1.16
URL <- "https://cran.r-project.org/src/contrib/Archive/SPARQL/SPARQL_1.16.tar.gz"
install.packages(URL, repos=NULL, type="source")
library(SPARQL)

#install agGraphSearch
install.packages( "devtools" )
devtools::install_github( "kumeS/agGraphSearch" , force = TRUE)
library( "agGraphSearch" )
```

**Comment by chimidata** [comment]
@kumeS 
I could success installing !!. 
Thank very much for your help.
And I apologize my poor English.
ありがとうございました．

**Comment by kumeS** [comment]
Hi @chimidata thank you for your reply.
If you have any problem, please feel free to contact me.
Satoshi
