### ISSUE TITLE
Can I get datasets from Google Drive?

### ISSUE THREAD

**Issue by chimidata** [kumeS/agGraphSearch#2]
In this time, I try to learn a usage of the package in the tutorial ([Wikidata] agGraphSearch tutorial: A workflow to use agGraphSearch and Wikidata with PolyInfo terms).
But I can't get datasets from Google Drive where you own. 
Then, if you allow me for using datasets above, please put them in the drive.

Thank you for your kind.

**Comment by kumeS** [comment]
Hi, @chimidata, 
sorry, my previous Google account has been deleted due to an affiliation change.
I am just uploading files to other Google Drive.
Please wait for a while till it finishes. Thank you.

**Comment by chimidata** [comment]
Thank you for your response.

I will wait for the announce that uploading files will be done.

Thank you.

**Comment by kumeS** [comment]
Hi, @chimidata, I have changed Google Drive URLs to new URLs. Please visit this GitHub page.
https://kumes.github.io/agGraphSearch/vignettes/agGraphSearch-Wikidata-WF.html
If you have any problem, please feel free to contact me.

**Comment by chimidata** [comment]
@kumeS , Thank you fior your response!
I can access the links of url above.
Well, I resume the tutorials. 
Kiitos hyvaa!
