### ISSUE TITLE
Issues occured in "Short tutorial: a workflow to use agGraphSearch for leukemia terms"

### ISSUE THREAD

**Issue by chimidata** [kumeS/agGraphSearch#3]
@kumeS san, I resume a tutorial titled above.
In section 3.5.2 'Individual network diagrams',  the programme shows a message below.
-----------------------------------------------------------------------------------------------------------------------------------
Warning message in dir.create(outputDir):
"cannot create dir 'agVisNetwork_急性リンパ性白血病.wd:Q180664_221209_files', reason 'Invalid argument'"
Warning message in dir.create(target_dir):
"cannot create dir 'agVisNetwork_急性リンパ性白血病.wd:Q180664_221209_files\htmlwidgets-1.5.4', reason 'Invalid argument'"
Error in normalizePath(path.expand(path), winslash, mustWork): path[1]="agVisNetwork_急性リンパ性白血病.wd:Q180664_221209_files/htmlwidgets-1.5.4": ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。
Traceback:

1. agVisNetwork(Graph = res5[[n]], Selected = Lab00, Browse = FALSE, 
 .     Output = TRUE, FilePath = FileName)
2. VIS %>% networkD3::saveNetwork(file = FilePath)
3. networkD3::saveNetwork(., file = FilePath)
4. htmlwidgets::saveWidget(network, file, selfcontained)
5. pandoc_save_markdown(html, file = file, libdir = libdir, background = background, 
 .     title = title)
6. lapply(rendered$dependencies, function(dep) {
 .     dep <- htmltools::copyDependencyToDir(dep, libdir, FALSE)
 .     dep <- htmltools::makeDependencyRelative(dep, dir, FALSE)
 .     dep
 . })
7. FUN(X[[i]], ...)
8. htmltools::copyDependencyToDir(dep, libdir, FALSE)
9. normalizePath(target_dir, "/", TRUE)
-----------------------------------------------------------------------------------------------------------------------------------

Well, I think that in Windows OS,  ":" could not be used in directory or folder or  file name.
(so that, in macOS, the programme is done. But another [WARNING] messages appear. That is "Deprecated: --self-contained. use --embed-resources --standalone".) 

Then, could you please fix the probelms.

Thank you for your kindness.

**Comment by kumeS** [comment]
Hi, @chimidata You should check the object you obtained; example fm2 etc. I think this code of short tutorial does not work well not because this SPARQL endpoint (http://kozaki-lab.osakac.ac.jp/agraph/NEDO_pj) is closed. Please check the following code first; "[[Wikidata] agGraphSearch tutorial: A workflow to use agGraphSearch and Wikidata with PolyInfo terms](https://kumes.github.io/agGraphSearch/vignettes/agGraphSearch-Wikidata-WF.html)". I am going to update the code of short tutorial that SPARQL query can be performed in the Wikidata official site. Please wait for a while.

**Comment by chimidata** [comment]
@kumeS san. I figure out your comment. 
So that, I first try to learn the tutorial "[[Wikidata] agGraphSearch tutorial: A workflow to use agGraphSearch and Wikidata with PolyInfo terms]". 
And I apologize for any inconvenience caused.
Anteeksi.
